[build]
  base = "/"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_GOOGLE_SHEET_URL = "https://script.google.com/macros/s/AKfycby7OHQbsWP1bHC7iWrWFvs8umUq3TpMee-Yk9v3iddvrQ03gehFtjwl635ntA-ufEdj/exec"